"""plugins_table

Revision ID: 170944baeb95
Revises: c0c6d558f399
Create Date: 2026-09-01 03:50:17.918968+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '170944baeb95'
down_revision: Union[str, None] = 'c0c6d558f399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wasm', sa.LargeBinary(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('signature_valid', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_name'), 'plugins', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugins_name'), table_name='plugins')
    op.drop_table('plugins')
    # ### end Alembic commands ###
