"""provider_test_runs

Revision ID: bd3bc1e9bf9e
Revises: 170944baeb95
Create Date: 2026-09-01 06:17:05.773853+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd3bc1e9bf9e'
down_revision: Union[str, None] = '170944baeb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_test_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('ok_count', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_test_runs_created_at'), 'provider_test_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_test_runs_kind'), 'provider_test_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_provider_test_runs_provider_id'), 'provider_test_runs', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_test_runs_provider_id'), table_name='provider_test_runs')
    op.drop_index(op.f('ix_provider_test_runs_kind'), table_name='provider_test_runs')
    op.drop_index(op.f('ix_provider_test_runs_created_at'), table_name='provider_test_runs')
    op.drop_table('provider_test_runs')
    # ### end Alembic commands ###
