"""provider_keys_is_active

Revision ID: c0c6d558f399
Revises: 0784ff7c0de9
Create Date: 2026-08-31 20:14:06.514414+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0c6d558f399'
down_revision: Union[str, None] = '0784ff7c0de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_keys_provider_id'), 'provider_keys', ['provider_id'], unique=False)
    op.add_column('api_keys', sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('groups', sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('mcp_servers', sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'is_active')
    op.drop_column('groups', 'is_active')
    op.drop_column('api_keys', 'is_active')
    op.drop_index(op.f('ix_provider_keys_provider_id'), table_name='provider_keys')
    op.drop_table('provider_keys')
    # ### end Alembic commands ###
